# Travis CI script
language: cpp
dist: trusty
sudo: required

# Compilers to test.
compiler:
  - g++

before_install:
  - sudo apt-get update -qq
  - sudo usermod -a -G audio travis
  - sudo apt-get remove --purge alsa-base pulseaudio
  - sudo apt-get install alsa-base pulseaudio
  - sudo alsa force-reload
  - sudo bash prep-dummy-soundcard.sh
  - sudo modprobe snd-dummy

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - build-essential
      - libasound2-dev
      - pkg-config

install:
    # libexadrums
    - wget http://http.us.debian.org/debian/pool/main/t/tinyxml2/libtinyxml2-dev_4.0.1-1_amd64.deb
    - wget http://http.us.debian.org/debian/pool/main/t/tinyxml2/libtinyxml2-4_4.0.1-1_amd64.deb
    - sudo dpkg -i libtinyxml2-4_4.0.1-1_amd64.deb
    - sudo dpkg -i libtinyxml2-dev_4.0.1-1_amd64.deb
    - export CXX="g++-7"
    - git clone git://github.com/SpintroniK/libeXaDrums.git
    - (mv libeXaDrums libexadrums; cd libexadrums; autoreconf -fi; ./configure --prefix=/usr --exec_prefix=/usr; make -j`nproc`; sudo make install; cd ..; rm -rf libexadrums)
    - git clone git://github.com/SpintroniK/eXaDrums.git
    - (mv eXaDrums exadrums; cd exadrums; mkdir $HOME/.eXaDrums; cp -r Data/ $HOME/.eXaDrums/; mkdir $HOME/.eXaDrums/Data/Rec;  sudo mkdir -p /usr/share/exadrums/Data/data/; sudo cp out.raw /usr/share/exadrums/Data/data/; cd .. ; rm -rf exadrums)

env:
  global:
    AUDIODEV=null

# Building libexadrums-tests
script:
    - export CXX="g++-7"
    - autoreconf -fi && ./configure --prefix=$HOME/local --exec_prefix=$HOME/local && make && make install
    - make check && make dist
    - sudo -E $HOME/local/bin/tests

