# Travis CI script
language: cpp
sudo: required
dist: xenial

# Compilers to test.
compiler:
  - g++

before_install:
  - sudo apt-get update -qq
  - sudo usermod -a -G audio travis
  - sudo apt-get install -y portaudio19-dev
  - sudo apt-get install -y libasound2-dev alsa-utils alsa-oss
  - sudo bash prep-dummy-soundcard.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - build-essential
      - libtinyxml2-dev
      - libasound2-dev
      - pkg-config

install:
    # libexadrums
    - export CXX="g++-7"
    - git clone git://github.com/SpintroniK/libeXaDrums.git
    - (mv libeXaDrums libexadrums; cd libexadrums; autoreconf -fi; ./configure --prefix=$HOME/local --exec_prefix=$HOME/local; make; make install; cd ..; rm -rf libexadrums)
    - git clone git://github.com/SpintroniK/eXaDrums.git
    - (mv eXaDrums exadrums; cd exadrums; mkdir $HOME/.eXaDrums; cp -r Data/ $HOME/.eXaDrums/; rm -rf exadrums)

env:
  global:
    AUDIODEV=null

# Building libexadrums-tests
script:
    - export CXX="g++-7"
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib
    - export PATH=$PATH:$HOME/local/bin
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/local/lib/pkgconfig
    - autoreconf -fi && ./configure --prefix=$HOME/local --exec_prefix=$HOME/local && make && make install
    - make check && make dist
    - $HOME/local/bin/tests

