# Travis CI script
language: cpp
sudo: required
dist: xenial

# Compilers to test.
compiler:
  - g++

before_install:
  - sudo apt-get update -qq
  - sudo usermod -a -G audio travis
  - sudo apt-get remove --purge alsa-base pulseaudio
  - sudo apt-get install alsa-base pulseaudio
  - sudo alsa force-reload
  - sudo apt-get remove --purge mysql* -y
  - sudo add-apt-repository ppa:ubuntu-audio-dev/alsa-daily -y
  - sudo apt-get update
  - sudo apt-get dist-upgrade -y
  - sudo bash prep-dummy-soundcard.sh
  - sudo modprobe snd-dummy

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - build-essential
      - libtinyxml2-dev
      - libasound2-dev
      - pkg-config

install:
    # libexadrums
    - export CXX="g++-7"
    - git clone git://github.com/SpintroniK/libeXaDrums.git
    - (mv libeXaDrums libexadrums; cd libexadrums; autoreconf -fi; ./configure --prefix=$HOME/local --exec_prefix=$HOME/local; make; make install; cd ..; rm -rf libexadrums)
    - git clone git://github.com/SpintroniK/eXaDrums.git
    - (mv eXaDrums exadrums; cd exadrums; mkdir $HOME/.eXaDrums; cp -r Data/ $HOME/.eXaDrums/; cd .. ; rm -rf exadrums; sed -i 's/default/null/g' $HOME/.eXaDrums/Data/alsaConfig.xml; more $HOME/.eXaDrums/Data/alsaConfig.xml)

env:
  global:
    AUDIODEV=null

# Building libexadrums-tests
script:
    - export CXX="g++-7"
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib
    - export PATH=$PATH:$HOME/local/bin
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/local/lib/pkgconfig
    - autoreconf -fi && ./configure --prefix=$HOME/local --exec_prefix=$HOME/local && make && make install
    - make check && make dist
    - $HOME/local/bin/tests

